Custom types support
svladykin/h2database pull request #1
Opened 2017-01-25 18:15 UTC by alexpaschenko

2017-01-25 20:57 UTC, svladykin requested changes

2017-01-25 20:57 UTC, svladykin commented on h2/src/main/org/h2/api/CustomType.java
> + * based on more 'primitive' {@link Value}s.
There are no more primitive or less primitive types. Just say that it is a conversion logic from builtin types.

2017-01-25 20:57 UTC, svladykin commented on h2/src/main/org/h2/api/ErrorCode.java
> +    public static final int CUSTOM_DATA_TYPE_ALREADY_EXISTS_1 = 90144;
Please provide meaningful examples for types. For example H2 does not have builtin support for complex numbers or matrices.

2017-01-25 20:57 UTC, svladykin commented on h2/src/main/org/h2/command/Parser.java
> +    private DropCustomDataType parseDropCustomDataType() {
Please replace the word `custom` with `value` everywhere.

2017-01-25 20:57 UTC, svladykin commented on h2/src/main/org/h2/command/Parser.java
> +            dataType = DataType.getTypeByName("JAVA_OBJECT");
This stuff looks suspicious

2017-01-25 20:57 UTC, svladykin commented on h2/src/main/org/h2/command/ddl/CreateCustomDataType.java
> +public class CreateCustomDataType extends DefineCommand {
`CreateValueType`

2017-01-25 20:57 UTC, svladykin commented on h2/src/main/org/h2/expression/Comparison.java
> +                        right = ValueExpression.get(((ExpressionColumn) left).getColumn().convert(r));
This change looks dirty as well.

2017-01-25 20:57 UTC, svladykin commented on h2/src/test/org/h2/test/testScript.sql
Overall the binding to a column looks wrong. The following stuff have to work without any columns:
```
SELECT CAST ('1 + 3i' AS COMPLEX) + '2 + 2i'
```

2017-01-26 09:32 UTC, alexpaschenko commented on h2/src/main/org/h2/command/Parser.java
> +            dataType = DataType.getTypeByName("JAVA_OBJECT");
Probably we should let implementations declare what type they boil down to, what do you think? Here `JAVA_OBJECT` is present simply as long as it is the most generic thing possible.

2017-01-26 09:35 UTC, alexpaschenko commented on h2/src/main/org/h2/expression/Comparison.java
> +                        right = ValueExpression.get(((ExpressionColumn) left).getColumn().convert(r));
I don't really see why. Before this change, `Column`'s `convert` did exactly the same thing as the old  conversion code here (and could have been used right away). Please see my thoughts about binding of the value type to column below. After all, here we clearly want to convert constant to type of the column, so asking the column to do the conversion seems rational.

2017-01-26 09:35 UTC, alexpaschenko commented on h2/src/test/org/h2/test/testScript.sql
The thing is, this cast (the part afrer `AS`, to be precise) is parsed exactly like any column in `CREATE TABLE` and actually even a `Column` object is created for a cast under the hood, so to me it is looks legit. Column knows what custom type is associated with it and can perform needed conversions transparently, without need for anyone from outside to bother about any new types. Do you have more concrete arguments why this binding is bad?

2017-01-26 11:35 UTC, svladykin commented on h2/src/test/org/h2/test/testScript.sql
Can you please add a test case like this?

2017-01-26 11:41 UTC, alexpaschenko commented on h2/src/main/org/h2/command/ddl/CreateCustomDataType.java
> +public class CreateCustomDataType extends DefineCommand {
Fixed to `CreateUserValueType`

2017-01-26 11:42 UTC, alexpaschenko commented on h2/src/main/org/h2/command/Parser.java
> +    private DropCustomDataType parseDropCustomDataType() {
Fixed

2017-01-26 11:42 UTC, alexpaschenko commented on h2/src/main/org/h2/api/CustomType.java
> + * based on more 'primitive' {@link Value}s.
Fixed

2017-01-26 11:42 UTC, alexpaschenko commented on h2/src/main/org/h2/api/ErrorCode.java
> +    public static final int CUSTOM_DATA_TYPE_ALREADY_EXISTS_1 = 90144;
Fixed

2017-01-27 05:52 UTC, svladykin commented
Ok, here is an example of what will not work with your column binding:
```sql
select complex(t.r, t.i) + '2 + 2i' from t
```
where `complex` returns user defined `Value` of type `COMPLEX`.

This is why your approach is broken.

2017-01-27 08:42 UTC, alexpaschenko commented
Erm. I'm sorry but why + operation should work on _objects_ in the first place? It seems to me that this thing is primarily for convenient comparisons and conversions on INSERT and not for trying to support quasi random stuff like adding one object to another.

2017-03-09 20:07 UTC, closed without merging